apiVersion: identityplatform.gcp.upbound.io/v1alpha1
kind: TenantInboundSAMLConfig
metadata:
  name: example
spec:
  forProvider:
    displayName: Display Name
    idpConfig:
    - idpCertificates:
      - x509Certificate: ${file("test-fixtures/rsa_cert.pem")}
      idpEntityId: tf-idp
      signRequest: true
      ssoUrl: https://example.com
    name: saml.tf-config
    spConfig:
    - callbackUri: https://example.com
      spEntityId: tf-sp
    tenant: ${google_identity_platform_tenant.tenant.name}
  providerConfigRef:
    name: example
