apiVersion: identityplatform.gcp.upbound.io/v1alpha1
kind: TenantOAuthIdPConfig
metadata:
  name: example
spec:
  forProvider:
    clientId: client-id
    clientSecret: secret
    displayName: Display Name
    enabled: true
    issuer: issuer
    name: oidc.oauth-idp-config
    tenant: ${google_identity_platform_tenant.tenant.name}
  providerConfigRef:
    name: example
