apiVersion: composer.gcp.upbound.io/v1beta2
kind: Environment
metadata:
  annotations:
    meta.upbound.io/example-id: composer/v1beta2/environment
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    config:
    - softwareConfig:
      - imageVersion: composer-1-airflow-2
    region: us-central1
