apiVersion: osconfig.gcp.upbound.io/v1alpha1
kind: PatchDeployment
metadata:
  name: example
spec:
  forProvider:
    instanceFilter:
    - all: true
    oneTimeSchedule:
    - executeTime: "2999-10-10T10:10:10.045123456Z"
    patchDeploymentId: patch-deploy
  providerConfigRef:
    name: example
