apiVersion: compute.gcp.upbound.io/v1alpha1
kind: NetworkPeeringRoutesConfig
metadata:
  name: example
spec:
  forProvider:
    exportCustomRoutes: true
    importCustomRoutes: true
    network: ${google_compute_network.network_primary.name}
    peering: peering1
  providerConfigRef:
    name: example
