apiVersion: appengine.gcp.upbound.io/v1alpha1
kind: Application
metadata:
  name: example
spec:
  forProvider:
    locationId: us-central
    project: ${google_project.my_project.project_id}
  providerConfigRef:
    name: example
