apiVersion: endpoints.gcp.upbound.io/v1alpha1
kind: Service
metadata:
  name: example
spec:
  forProvider:
    openapiConfig: ${file("openapi_spec.yml")}
    project: project-id
    serviceName: api-name.endpoints.project-id.cloud.goog
  providerConfigRef:
    name: example
