apiVersion: accessapproval.gcp.upbound.io/v1alpha1
kind: ProjectSettings
metadata:
  name: example
spec:
  forProvider:
    enrolledServices:
    - cloudProduct: all
      enrollmentLevel: BLOCK_ALL
    notificationEmails:
    - testuser@example.com
    - example.user@example.com
    projectId: my-project-name
  providerConfigRef:
    name: example
