apiVersion: logging.gcp.upbound.io/v1alpha1
kind: OrganizationBucketConfig
metadata:
  name: example
spec:
  forProvider:
    bucketId: _Default
    location: global
    organization: ${data.google_organization.default.organization}
    retentionDays: 30
  providerConfigRef:
    name: example
