apiVersion: identityplatform.gcp.upbound.io/v1beta1
kind: InboundSAMLConfig
metadata:
  annotations:
    meta.upbound.io/example-id: identityplatform/v1beta1/inboundsamlconfig
  labels:
    testing.upbound.io/example-name: saml_config
  name: saml-config
spec:
  forProvider:
    displayName: Display Name
    idpConfig:
    - idpCertificates:
      - x509CertificateSecretRef:
          key: attribute.rsa_cert.pem
          name: example-secret
          namespace: upbound-system
      idpEntityId: tf-idp
      signRequest: true
      ssoUrl: https://example.com
    name: saml.tf-config
    spConfig:
    - callbackUri: https://example.com
      spEntityId: tf-sp
