apiVersion: monitoring.gcp.upbound.io/v1beta1
kind: Service
metadata:
  annotations:
    meta.upbound.io/example-id: monitoring/v1beta1/service
  labels:
    testing.upbound.io/example-name: my_service
  name: my-service
spec:
  forProvider:
    basicService:
    - serviceLabels:
        module_id: another-module-id
      serviceType: APP_ENGINE
    displayName: My Service my-service
    userLabels:
      my_key: my_value
      my_other_key: my_other_value
