apiVersion: cloudrun.gcp.upbound.io/v1beta1
kind: Service
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: us-central1
    template:
    - spec:
      - containers:
        - image: us-docker.pkg.dev/cloudrun/container/hello
    traffic:
    - latestRevision: true
      percent: 100
