apiVersion: deploymentmanager.gcp.upbound.io/v1alpha1
kind: Deployment
metadata:
  name: example
spec:
  forProvider:
    labels:
    - key: foo
      value: bar
    name: my-deployment
    target:
    - config:
      - content: ${file("path/to/config.yml")}
  providerConfigRef:
    name: example
