apiVersion: cloudrun.gcp.upbound.io/v1beta1
kind: Service
metadata:
  annotations:
    meta.upbound.io/example-id: cloudrun/v1beta1/service
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    location: us-central1
    template:
    - spec:
      - containers:
        - image: us-docker.pkg.dev/cloudrun/container/hello
    traffic:
    - latestRevision: true
      percent: 100
