apiVersion: notebooks.gcp.upbound.io/v1alpha1
kind: Environment
metadata:
  name: example
spec:
  forProvider:
    containerImage:
    - repository: gcr.io/deeplearning-platform-release/base-cpu
    location: us-west1-a
    name: notebooks-environment
  providerConfigRef:
    name: example
